# Shell variables
# Generated by 'wal'
wallpaper='/home/claudio/Immagini/wallpaper.png'

# Special
background='#1f212a'
foreground='#d1bdee'
cursor='#d1bdee'

# Colors
color0='#1f212a'
color1='#4DE275'
color2='#626688'
color3='#A46DAF'
color4='#DB6EB0'
color5='#68A2B4'
color6='#7CCADD'
color7='#d1bdee'
color8='#9284a6'
color9='#4DE275'
color10='#626688'
color11='#A46DAF'
color12='#DB6EB0'
color13='#68A2B4'
color14='#7CCADD'
color15='#d1bdee'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
