--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/claudio/Immagini/wallpaper.png"

-- Special
background="#1f212a"
foreground="#d1bdee"
cursor="#d1bdee"

-- Colors
color0="#1f212a"
color1="#4DE275"
color2="#626688"
color3="#A46DAF"
color4="#DB6EB0"
color5="#68A2B4"
color6="#7CCADD"
color7="#d1bdee"
color8="#9284a6"
color9="#4DE275"
color10="#626688"
color11="#A46DAF"
color12="#DB6EB0"
color13="#68A2B4"
color14="#7CCADD"
color15="#d1bdee"
